import * as flsFunctions from './modules/functions.js'
import './modules/dropdown.js'
import '../../node_modules/bootstrap/js/src/base-component.js'
import '../../node_modules/bootstrap/js/src/collapse.js'
import '../../node_modules/bootstrap/js/src/dropdown.js'
